services:
  - type: web
    name: tiktok-downloader-api
    env: node
    region: oregon  # You can also use: ohio, frankfurt, singapore
    plan: free
    buildCommand: npm install
    startCommand: node app.js 
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: TIKWM_API
        value: https://tikwm.com/api
    autoDeploy: true
    branch: main
